[build]
  command = "npm run build:netlify"
  publish = "dist"

[build.environment]
  VITE_BASE = "/"

# Handles SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript"
