[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # No need to set VITE_BASE as it will use the default from .env file

# Handles SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
